language: minimal
services: docker
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.25.5
  global:
  - secure: qrg2ZhnbNKjyTNP2w6wSvixJ2ZYVhhtMjV/fXU/5OqiGIlzLUZ1RMM62Zak6Fygn93/ce6N2Frrahb/1phKNGf4Xm/iIMhqnoqQzOiK2iXR/W+/ucvd7GhF/lbz9GALoTvNSFcdkVfSYCyiJo70HMYHShA42ji9ubN5qRmhs5yX71xyjna0Jaw/fq9lO40mwlnGitNxJbpsKjMrEu5egnv8/rQ/momHBpZgVb311+lFN/1rOgYek0acqL2w9t4Ll9cMoGINyHDf5C0Eze9i7KRzmt9U7f7rEFR5iRLT82BjKluB9IfldpSH1GYdgpMX5iNjsYq1oq+3DEY1xli84MEAmahhILW2E5768i34M0GStHO4/wZ0K/UbuMCv3QDrKs9Y6jATQ4AxcZr0KDhiPJlBeXWfXmMTfe/GOXhDjCiyhdUAIHIwdLYwfQoryLlNA7/Xp3fALPyJCXoigN48OklsfCGlVouUI5k0LupY5eCyEH7Jyv1emKSItTL1H73TBXA/NEvLgO3KbumQIwUM86KA7CCHO3x7R2GIOJlvMcVsAfYucHjkoV4zs0IILjRFkjz6u5wXiUjh3qk1hMmEJIHw1XnoIKcyef9sLdrPJrB9xqnsrMfnl3kq5GA/grExgDmndXh+0CQuyj4wDsYx0rDQ5obAdcad0BYlJEg+S7zg=
  - secure: PoASfEZpchqVYszGQeJfBHOVRjP2z9ckBiDF4LhW/PPjJ9DaCn4gzajyF4Ht9baEOrwC9A8sswAgFL389CY2B3ltiF21HNMvGJ47DuMP+MVsaQJTbDxujW+i/isAk05XAwMerwYGUhGDgJiMDpJ+zzONWvRr6kpLWwqB1MHVTPVbKym0xLb60NA9qZ7+0iNalqzXAs8IvS9n1FR7B25w6OrbRCWwafbFWp/uafXRQyT5pSX6dXD9u4T1rbnLgLjZuYEqbIL7IWn+OQ2erpr4hdlj1EjN2xPaMTY0R8HRyXHfP8FJFAuk59d9hHVzW+YY4vUJItOm6CldMAtuLK4Wh7hZr7KJiXPNddaTWmTnYem5divuxfVSJopWSyyBXHEp2Afm7esZ6EDYCWSS52yUkwZQZKQ3T9pHntkPpWz4hxEw4A/QDsUNHCW3KROFKvnU6N7Kdt3wkqevTAzi5XHqoCTnnQzYKIT8CdkvUbTqEpqYyb0BIxemaT1WcWzTJbodiE5b6Dsdlpt2Ici8n2EdVrd/CJd7K7LnrDusH/WmdxrDFI7pdXyYN1BtZBlnwPp39ibNGHpR3aZiAqaRqB9xaohvaMlDZPNwgvoLJh+eXcZi/HsTZ2MKdqhFMwsKwNGTMJHeVQI0FxHY+xgbKM/3N7XnR+YZ6bCjzWt7b0SSoN0=
  - secure: Wn0hltoNMNgcOBn+ANJjNdV5MEoWR9u3dlrRARwO9Bvyz+O75ZMxRSliNU00sMiUUIcIPuUERrXMFYZrnwK++TveU2weRSwyRYd5TO3J13Zv1vl5JGb1An1XXLAohn0uOQbjWZOsSm+QM9HwWkB9/Fp8MzlfUEg+qfMSgtbwAgJMgPgCKWp0hWCnwrWDX5JFPqtcdGqdfNlXp3Vk346haCcLnaswRVv+KoHucnNtf6c9zOdS7zwE4Xql1yJ7PFIkrpl1q9UqjiFc8Q5sKjP73TZGRvfyGUWQbhBAxIYeR/Q/gEctCNzqjzKhCAcbF/KKutOzfprA1+Br96W9DUEtOX2VN9Y6RR4vMfEyV31VwFj7dHtKZxamP5P1klW7/fCcbh8Ao9HVCCleqVP1ClZ5F9b7LEEgr7XIaOrP4oTD8DIyRFR4TUgFqn5lFsPkrF2mKO6vSTjxt803z/xNTO3EpmCte9xVP/dWgWEdfgK1H+GlPrx7u7jkhWH/GvZKb+M4xbgFOduPU841IG5it3UU0FihQzJc/XIrw0iiqceg2zVQz1xUdLyi18/hbpoML/TNoavVSuspiYgmkL3uyZMUy+pHA7DkeiUpSCtT3CVZQssEv/HogHGp5domZPRiDg3RgfKLBX3EszqMKTMNpS+lp3PpaW8koIDNaIVBjyyajhg=
  - secure: XGhVsU0kqQCqcoDklnmjkWHKvbe0q0RmbMN9z6iyS7rXRKv4SUt39wsm0pgk/Ub6+49+qD5zO/992i2mfEwrDnDqfMwfHrDgc/YYpUWMZrHBfBbn6Iu+HPvj5Np2dKc0XiEfgwoCUNaqXlvt9MfExe1IUZBmwA+bpzsvsusl7lya+AdzvR0rBg8qK0BQ247L6Fehl0K7xgH1DR8jmBNubzoROCdwkVBrnAPSYIV6tA3i02QU4AVfDJOVotKpxy2GKTzWCrXkgGhhgFmT8+wxAK3D15MY89W+2a966cbrOcKDwLkF5wPtsrUg3QZBUOBT3wmw6PvUvVbGoUiZn3ELffO9p4N5EivVc/TCtaNqy+29JirHxa0YqrxqHd1Bg+Hqs8QZqg3cGjki1ZlcQ6UtVNW6rCDypJgXrEi0kEAo6R+mqi0eR0eowlcKoRnuEkRBVr15Cqc0/27wDCD8sDOpy0w2EnzBEp6M70FN8KPAzkVyVv4d3AnkaQo420VCYqVkDFaQmhwLtWUROWZJeXyJk/UIwv7g9OYcGQRxUhMc89hZ96+HdOUuT/wxp7XdsjoNe7Xz1tuMVig2AcJ8sczcJr4E0l+G2glXugA0As3/SZq39wTam3i8Zkc/gEb8f2mKzphpMt81mLMs853NunW7zIfsVDeaodJC9Mx9MnH+VYg=
  - secure: wzSgayUazqL7NwDF9BTQC0xwQZJmefMx8GnqFhKhdH+fxhsKysawR/+54ArTd5SbQlo1RhzAhts+0JbBuN3aogeQKPyWocaItiIfsyCHjNRx3BmUk4W5KR2XAF5xXPA34WCa54XksS4qaEYoe905qvyDBUIFrEA0hy8k7GChusUgNmL1NG3eSGFse9OOQQTSnKklFfKC5gkf39VKf38j+3jWOEhgkElwtN4NyO70Egv49S+qTYBOHPRRHVgXIhk6DpfpLid+hbR83Yp5mfsdEAJ8bwR9Cho9mOftMgpUDgRmZ1UTkcJ29g5fEtxX+HslP/s8TN8i5l16OfsRJJEyJldAutrsC/B1oopICJm0j4mH21qYTSiTVQhL6tDpFAGwIUec/KsdJEeIOPmoaTl6RNIfA+d8C9b/cAvBmK8rG5zNaRt5x9AISdggE5kaprV+kAJ9TV86YxZMXJf87+ui31YzfwvGe/v+kAtR4O/Rdrctdb0uK7dZwGL/W8tjrh29LNMDK+UK+MylaQ3zEwPlV9WUmjceizdkzH2Z3a95MigAiKt56qS2kGptBAsL2JJlGqQ6LqsK1oTuLyj1UCA5m+vlzErKB3sXTiy/b8Y7uBw1glOyZiORmIC5hgZcpI0OKtpGcHS+HlbFIukB9LeXQEM2VW5kTFHXrNdhV2+evY8=
before_install:
- docker -v && docker-compose -v
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
- chmod +x ./aws-iam-authenticator
- sudo mv ./aws-iam-authenticator /usr/local/bin/
- mkdir -p ${HOME}/.kube
- cp udacity-c3-deployment/eks/kubeconfig-template.yaml ${HOME}/.kube/config
- export KUBECONFIG=${HOME}/.kube/config
- kubectl --kubeconfig=udacity-c3-deployment/eks/kubeconfig-template.yaml get deployments
jobs:
  include:
  - stage: dockerize
    script:
    - cd udacity-c3-deployment/docker
    - docker-compose -f docker-compose-build.yaml build --parallel
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
    - docker-compose -f docker-compose-build.yaml push
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
    - docker-compose -f docker-compose-build.yaml push
  - stage: aws_eks_deploy
    script:
    - cd udacity-c3-deployment/k8s
    - kubectl apply -f backend-feed-service.yaml
    - kubectl apply -f backend-user-service.yaml
    - kubectl apply -f frontend-service.yaml
    - kubectl apply -f reverseproxy-service.yaml
    - kubectl apply -f aws-secret.yaml
    - kubectl apply -f env-configmap.yaml
    - kubectl apply -f env-secret.yaml
    - kubectl apply -f backend-feed-deployment.yaml
    - kubectl apply -f backend-user-deployment.yaml
    - kubectl apply -f frontend-deployment.yaml
    - kubectl apply -f reverseproxy-deployment.yaml
branches:
  only:
  - master
